<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8CBSCDJ" name="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest" tests="7" failures="0" timestamp="21 Mar 2017 16:33:50 GMT" time="0.101" errors="0">
  <testcase name="testAuthUserWithCorrectCredentialsShouldBeSuccessful" time="0.072" classname="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest"/>
  <testcase name="testRegisterUserShouldFailIfInternalServerErrorOccurred" time="0.002" classname="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest"/>
  <testcase name="testAuthUserWithInvalidCredentialsShouldFail" time="0.002" classname="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest"/>
  <testcase name="testRegisterUserWithInvalidCredentialsShouldFail" time="0.007" classname="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest"/>
  <testcase name="testRegisterUserShouldFailIfConnectionErrorOccurred" time="0.003" classname="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest"/>
  <testcase name="testAuthUserShouldFailIfConnectionErrorOccurred" time="0.015" classname="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest"/>
  <testcase name="testRegisterUserWithCorrectParametersShouldBeSuccessful" time="0.000" classname="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest"/>
</testsuite>
