<html>
<head>
<title>TestNG:  Command line test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Command line test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>27/0/0</td>
</tr><tr>
<td>Started on:</td><td>Tue Mar 21 19:33:47 EAT 2017</td>
</tr>
<tr><td>Total time:</td><td>2 seconds (2323 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowNoConnectionExceptionIfPoulpeUnavailable()'><b>authenticateShouldThrowNoConnectionExceptionIfPoulpeUnavailable</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:110)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowNoConnectionExceptionIfPoulpeUnavailable(PoulpeAuthPluginTest.java:185)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1626883", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1626883'><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:110)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowNoConnectionExceptionIfPoulpeUnavailable(PoulpeAuthPluginTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred()'><b>authenticateShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:113)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred(PoulpeAuthPluginTest.java:196)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:110)
	... 35 more
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace5840411", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace5840411'><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:113)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred(PoulpeAuthPluginTest.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:110)
	... 35 more
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectParametersShouldNotBeConfigured()'><b>pluginWithIncorrectParametersShouldNotBeConfigured</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectParametersShouldThrowException()'><b>pluginWithIncorrectParametersShouldThrowException</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can&apos;t apply configuration: Url should not be null.
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:63)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectParametersShouldThrowException(PoulpeAuthPluginTest.java:79)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can&apos;t apply configuration: Url should not be null.
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.applyConfiguration(PoulpeAuthPlugin.java:168)
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:52)
	... 35 more
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace8823287", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace8823287'><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Url should not be null.
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:63)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectParametersShouldThrowException(PoulpeAuthPluginTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Url should not be null.
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.applyConfiguration(PoulpeAuthPlugin.java:168)
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:52)
	... 35 more
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectUrlShouldNotBeConfigured()'><b>pluginWithIncorrectUrlShouldNotBeConfigured</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectUrlShouldThrowException()'><b>pluginWithIncorrectUrlShouldThrowException</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can&apos;t apply configuration: Incorrect format for Url value.
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:63)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectUrlShouldThrowException(PoulpeAuthPluginTest.java:97)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can&apos;t apply configuration: Incorrect format for Url value.
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.applyConfiguration(PoulpeAuthPlugin.java:170)
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:52)
	... 35 more
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace23447691", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace23447691'><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Incorrect format for Url value.
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:63)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectUrlShouldThrowException(PoulpeAuthPluginTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Incorrect format for Url value.
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.applyConfiguration(PoulpeAuthPlugin.java:170)
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:52)
	... 35 more
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowNoConnectionExceptionIfPoulpeUnavailable()'><b>registerUserShouldThrowNoConnectionExceptionIfPoulpeUnavailable</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:79)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerUser(PoulpeAuthPlugin.java:64)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowNoConnectionExceptionIfPoulpeUnavailable(PoulpeAuthPluginTest.java:134)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace19249292", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace19249292'><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:79)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerUser(PoulpeAuthPlugin.java:64)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowNoConnectionExceptionIfPoulpeUnavailable(PoulpeAuthPluginTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred()'><b>registerUserShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:82)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerUser(PoulpeAuthPlugin.java:64)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred(PoulpeAuthPluginTest.java:144)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:79)
	... 36 more
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace19015978", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace19015978'><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:82)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerUser(PoulpeAuthPlugin.java:64)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred(PoulpeAuthPluginTest.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:79)
	... 36 more
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testAuthUserShouldFailIfConnectionErrorOccurred()'><b>testAuthUserShouldFailIfConnectionErrorOccurred</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException: Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getAuthResult(PoulpeAuthService.java:138)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.authenticate(PoulpeAuthService.java:96)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testAuthUserShouldFailIfConnectionErrorOccurred(PoulpeAuthServiceTest.java:142)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace32404541", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace32404541'><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException: Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getAuthResult(PoulpeAuthService.java:138)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.authenticate(PoulpeAuthService.java:96)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testAuthUserShouldFailIfConnectionErrorOccurred(PoulpeAuthServiceTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testAuthUserWithCorrectCredentialsShouldBeSuccessful()'><b>testAuthUserWithCorrectCredentialsShouldBeSuccessful</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testAuthUserWithInvalidCredentialsShouldFail()'><b>testAuthUserWithInvalidCredentialsShouldFail</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.testConfigure()'><b>testConfigure</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfConnectionErrorOccurred()'><b>testRegisterUserShouldFailIfConnectionErrorOccurred</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException: Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getRegistrationResult(PoulpeAuthService.java:176)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.registerUser(PoulpeAuthService.java:80)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfConnectionErrorOccurred(PoulpeAuthServiceTest.java:84)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace23478577", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace23478577'><pre>org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException: Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getRegistrationResult(PoulpeAuthService.java:176)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.registerUser(PoulpeAuthService.java:80)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfConnectionErrorOccurred(PoulpeAuthServiceTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfInternalServerErrorOccurred()'><b>testRegisterUserShouldFailIfInternalServerErrorOccurred</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest</td>
<td><div><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getRegistrationResult(PoulpeAuthService.java:174)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.registerUser(PoulpeAuthService.java:80)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfInternalServerErrorOccurred(PoulpeAuthServiceTest.java:93)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace8279419", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace8279419'><pre>org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getRegistrationResult(PoulpeAuthService.java:174)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.registerUser(PoulpeAuthService.java:80)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfInternalServerErrorOccurred(PoulpeAuthServiceTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
</pre></div></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserWithCorrectParametersShouldBeSuccessful()'><b>testRegisterUserWithCorrectParametersShouldBeSuccessful</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserWithInvalidCredentialsShouldFail()'><b>testRegisterUserWithInvalidCredentialsShouldFail</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest.testSendAuthRequestWithInvalidCredentialsShouldFail()'><b>testSendAuthRequestWithInvalidCredentialsShouldFail</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest.testSendAuthRequestWithValidCredentialsShouldBeSuccessful()'><b>testSendAuthRequestWithValidCredentialsShouldBeSuccessful</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest.testSendRegistrationRequestShouldBeSuccessful()'><b>testSendRegistrationRequestShouldBeSuccessful</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest.testSendRegistrationRequestWithBadResponseShouldFail()'><b>testSendRegistrationRequestWithBadResponseShouldFail</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest.testSendRegistrationRequestWithValidationErrorResponseShouldFail()'><b>testSendRegistrationRequestWithValidationErrorResponseShouldFail</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.translateLabelWithExistingTranslation()'><b>translateLabelWithExistingTranslation</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.translateLabelWithoutExistingTranslation()'><b>translateLabelWithoutExistingTranslation</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.userShouldNotBeAuthenticatedIfSomeErrorOccurred()'><b>userShouldNotBeAuthenticatedIfSomeErrorOccurred</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.userShouldNotBeRegisteredIfSomeErrorOccurred()'><b>userShouldNotBeRegisteredIfSomeErrorOccurred</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.userWithCorrectParametersShouldBeAuthenticated()'><b>userWithCorrectParametersShouldBeAuthenticated</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
<tr>
<td title='org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.userWithCorrectParametersShouldBeRegistered()'><b>userWithCorrectParametersShouldBeRegistered</b><br>Test class: org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest</td>
<td></td>
<td>0</td>
<td>org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f</td></tr>
</table><p>
</body>
</html>